# Removed Protocol 4, 6, 17
# This script is designed to manage and secure all incoming network traffic to your Windows system. It ensures that only the traffic
# using protocols 4, 6, and 17 is allowed, and every other protocol is blocked.




New-NetFirewallRule -DisplayName "Block Protocol 0 (HOPOPT)"    -Direction Inbound -Action Block -Protocol 0  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 1 (ICMP)"      -Direction Inbound -Action Block -Protocol 1  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 2 (IGMP)"      -Direction Inbound -Action Block -Protocol 2  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 3 (GGP)"       -Direction Inbound -Action Block -Protocol 3  -Profile Any

New-NetFirewallRule -DisplayName "Block Protocol 5 (ST)"        -Direction Inbound -Action Block -Protocol 5  -Profile Any

New-NetFirewallRule -DisplayName "Block Protocol 7 (CBT)"       -Direction Inbound -Action Block -Protocol 7  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 8 (EGP)"       -Direction Inbound -Action Block -Protocol 8  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 9 (IGP)"       -Direction Inbound -Action Block -Protocol 9  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 10 (BBN-RCC-MON)" -Direction Inbound -Action Block -Protocol 10 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 11 (NVP-II)"     -Direction Inbound -Action Block -Protocol 11 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 12 (PUP)"        -Direction Inbound -Action Block -Protocol 12 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 13 (ARGUS)"      -Direction Inbound -Action Block -Protocol 13 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 14 (EMCON)"      -Direction Inbound -Action Block -Protocol 14 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 15 (XNET)"       -Direction Inbound -Action Block -Protocol 15 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 16 (CHAOS)"      -Direction Inbound -Action Block -Protocol 16 -Profile Any

New-NetFirewallRule -DisplayName "Block Protocol 18 (MUX)"        -Direction Inbound -Action Block -Protocol 18 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 19 (DCN-MEAS)"   -Direction Inbound -Action Block -Protocol 19 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 20 (HMP)"        -Direction Inbound -Action Block -Protocol 20 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 21 (PRM)"        -Direction Inbound -Action Block -Protocol 21 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 22 (XNS-IDP)"    -Direction Inbound -Action Block -Protocol 22 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 23 (TRUNK-1)"    -Direction Inbound -Action Block -Protocol 23 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 24 (TRUNK-2)"    -Direction Inbound -Action Block -Protocol 24 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 25 (LEAF-1)"     -Direction Inbound -Action Block -Protocol 25 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 26 (LEAF-2)"     -Direction Inbound -Action Block -Protocol 26 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 27 (RDP)"        -Direction Inbound -Action Block -Protocol 27 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 28 (IRTP)"       -Direction Inbound -Action Block -Protocol 28 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 29 (ISO-TP4)"    -Direction Inbound -Action Block -Protocol 29 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 30 (NETBLT)"     -Direction Inbound -Action Block -Protocol 30 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 31 (MFE-NSP)"   -Direction Inbound -Action Block -Protocol 31 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 32 (MERIT-INP)" -Direction Inbound -Action Block -Protocol 32 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 33 (DCCP)"      -Direction Inbound -Action Block -Protocol 33 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 34 (3PC)"       -Direction Inbound -Action Block -Protocol 34 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 35 (IDPR)"      -Direction Inbound -Action Block -Protocol 35 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 36 (XTP)"       -Direction Inbound -Action Block -Protocol 36 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 37 (DDP)"       -Direction Inbound -Action Block -Protocol 37 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 38 (IDPR-CMTP)" -Direction Inbound -Action Block -Protocol 38 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 39 (TP++)"      -Direction Inbound -Action Block -Protocol 39 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 40 (IL)"        -Direction Inbound -Action Block -Protocol 40 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 41 (IPv6)"      -Direction Inbound -Action Block -Protocol 41 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 42 (SDRP)"      -Direction Inbound -Action Block -Protocol 42 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 43 (IPv6-Route)"-Direction Inbound -Action Block -Protocol 43 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 44 (IPv6-Frag)" -Direction Inbound -Action Block -Protocol 44 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 45 (IDRP)"      -Direction Inbound -Action Block -Protocol 45 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 46 (RSVP)"      -Direction Inbound -Action Block -Protocol 46 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 47 (GRE)"       -Direction Inbound -Action Block -Protocol 47 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 48 (MHRP)"      -Direction Inbound -Action Block -Protocol 48 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 49 (Reserved)"  -Direction Inbound -Action Block -Protocol 49 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 50 (ESP)"       -Direction Inbound -Action Block -Protocol 50 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 51 (AH)"        -Direction Inbound -Action Block -Protocol 51 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 52 (I-NLSP)"    -Direction Inbound -Action Block -Protocol 52 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 53 (SwIPe)"     -Direction Inbound -Action Block -Protocol 53 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 54 (NARP)"      -Direction Inbound -Action Block -Protocol 54 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 55 (MOBILE)"    -Direction Inbound -Action Block -Protocol 55 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 56 (TLSP)"      -Direction Inbound -Action Block -Protocol 56 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 57 (SKIP)"      -Direction Inbound -Action Block -Protocol 57 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 58 (IPv6-ICMP)" -Direction Inbound -Action Block -Protocol 58 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 59 (IPv6-NoNxt)"-Direction Inbound -Action Block -Protocol 59 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 60 (IPv6-Opts)" -Direction Inbound -Action Block -Protocol 60 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 61 (Any Host Internal Protocol)" -Direction Inbound -Action Block -Protocol 61 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 62 (CFTP)"                     -Direction Inbound -Action Block -Protocol 62 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 63 (Any Local Network)"         -Direction Inbound -Action Block -Protocol 63 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 64 (SAT-EXPAK)"                 -Direction Inbound -Action Block -Protocol 64 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 65 (KRYPTOLAN)"                 -Direction Inbound -Action Block -Protocol 65 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 66 (RVD)"                       -Direction Inbound -Action Block -Protocol 66 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 67 (IPPC)"                      -Direction Inbound -Action Block -Protocol 67 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 68 (Any Distributed File System)"-Direction Inbound -Action Block -Protocol 68 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 69 (SAT-MON)"                   -Direction Inbound -Action Block -Protocol 69 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 70 (VISA)"                      -Direction Inbound -Action Block -Protocol 70 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 71 (IPCV)"                      -Direction Inbound -Action Block -Protocol 71 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 72 (CPNX)"                      -Direction Inbound -Action Block -Protocol 72 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 73 (CPHB)"                      -Direction Inbound -Action Block -Protocol 73 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 74 (WSN)"                       -Direction Inbound -Action Block -Protocol 74 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 75 (PVP)"                       -Direction Inbound -Action Block -Protocol 75 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 76 (BR-SAT-MON)"                -Direction Inbound -Action Block -Protocol 76 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 77 (SUN-ND)"                    -Direction Inbound -Action Block -Protocol 77 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 78 (WB-MON)"                    -Direction Inbound -Action Block -Protocol 78 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 79 (WB-EXPAK)"                  -Direction Inbound -Action Block -Protocol 79 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 80 (ISO-IP)"                    -Direction Inbound -Action Block -Protocol 80 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 81 (VMTP)"                      -Direction Inbound -Action Block -Protocol 81 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 82 (SECURE-VMTP)"               -Direction Inbound -Action Block -Protocol 82 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 83 (VINES)"                     -Direction Inbound -Action Block -Protocol 83 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 84 (TTP)"                       -Direction Inbound -Action Block -Protocol 84 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 85 (NSFNET-IGP)"                -Direction Inbound -Action Block -Protocol 85 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 86 (DGP)"                      -Direction Inbound -Action Block -Protocol 86 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 87 (TCF)"                      -Direction Inbound -Action Block -Protocol 87 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 88 (EIGRP)"                    -Direction Inbound -Action Block -Protocol 88 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 89 (OSPFIGP)"                  -Direction Inbound -Action Block -Protocol 89 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 90 (Sprite-RPC)"               -Direction Inbound -Action Block -Protocol 90 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 91 (LARP)"       -Direction Inbound -Action Block -Protocol 91  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 92 (MTP)"        -Direction Inbound -Action Block -Protocol 92  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 93 (AX.25)"      -Direction Inbound -Action Block -Protocol 93  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 94 (IPIP)"       -Direction Inbound -Action Block -Protocol 94  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 95 (MICP)"       -Direction Inbound -Action Block -Protocol 95  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 96 (SCC-SP)"     -Direction Inbound -Action Block -Protocol 96  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 97 (ETHERIP)"    -Direction Inbound -Action Block -Protocol 97  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 98 (Encapsulation)" -Direction Inbound -Action Block -Protocol 98  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 99 (GMTP)"       -Direction Inbound -Action Block -Protocol 99  -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 100 (IFMP)"      -Direction Inbound -Action Block -Protocol 100 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 101 (PNNI)"      -Direction Inbound -Action Block -Protocol 101 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 102 (PIM)"       -Direction Inbound -Action Block -Protocol 102 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 103 (ARIS)"      -Direction Inbound -Action Block -Protocol 103 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 104 (SCPS)"      -Direction Inbound -Action Block -Protocol 104 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 105 (QNX)"       -Direction Inbound -Action Block -Protocol 105 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 106 (A/N)"       -Direction Inbound -Action Block -Protocol 106 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 107 (IPComp)"    -Direction Inbound -Action Block -Protocol 107 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 108 (SNP)"       -Direction Inbound -Action Block -Protocol 108 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 109 (Compaq-Peer)" -Direction Inbound -Action Block -Protocol 109 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 110 (IPX-in-IP)"   -Direction Inbound -Action Block -Protocol 110 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 111 (VRRP)"      -Direction Inbound -Action Block -Protocol 111 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 112 (PGM)"       -Direction Inbound -Action Block -Protocol 112 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 113 (Zero-Hop)"  -Direction Inbound -Action Block -Protocol 113 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 114 (L2TP)"      -Direction Inbound -Action Block -Protocol 114 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 115 (DDX)"       -Direction Inbound -Action Block -Protocol 115 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 116 (IATP)"      -Direction Inbound -Action Block -Protocol 116 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 117 (STP)"       -Direction Inbound -Action Block -Protocol 117 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 118 (SRP)"       -Direction Inbound -Action Block -Protocol 118 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 119 (UTI)"       -Direction Inbound -Action Block -Protocol 119 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 120 (SMP)"       -Direction Inbound -Action Block -Protocol 120 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 121 (Unassigned)" -Direction Inbound -Action Block -Protocol 121 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 122 (Unassigned)" -Direction Inbound -Action Block -Protocol 122 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 123 (Unassigned)" -Direction Inbound -Action Block -Protocol 123 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 124 (Unassigned)" -Direction Inbound -Action Block -Protocol 124 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 125 (Unassigned)" -Direction Inbound -Action Block -Protocol 125 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 126 (Unassigned)" -Direction Inbound -Action Block -Protocol 126 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 127 (Unassigned)" -Direction Inbound -Action Block -Protocol 127 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 128 (Unassigned)" -Direction Inbound -Action Block -Protocol 128 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 129 (Unassigned)" -Direction Inbound -Action Block -Protocol 129 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 130 (Unassigned)" -Direction Inbound -Action Block -Protocol 130 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 131 (Unassigned)" -Direction Inbound -Action Block -Protocol 131 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 132 (Unassigned)" -Direction Inbound -Action Block -Protocol 132 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 133 (Unassigned)" -Direction Inbound -Action Block -Protocol 133 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 134 (Unassigned)" -Direction Inbound -Action Block -Protocol 134 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 135 (Unassigned)" -Direction Inbound -Action Block -Protocol 135 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 136 (Unassigned)" -Direction Inbound -Action Block -Protocol 136 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 137 (Unassigned)" -Direction Inbound -Action Block -Protocol 137 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 138 (Unassigned)" -Direction Inbound -Action Block -Protocol 138 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 139 (Unassigned)" -Direction Inbound -Action Block -Protocol 139 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 140 (Unassigned)" -Direction Inbound -Action Block -Protocol 140 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 141 (Unassigned)" -Direction Inbound -Action Block -Protocol 141 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 142 (Unassigned)" -Direction Inbound -Action Block -Protocol 142 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 143 (Unassigned)" -Direction Inbound -Action Block -Protocol 143 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 144 (Unassigned)" -Direction Inbound -Action Block -Protocol 144 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 145 (Unassigned)" -Direction Inbound -Action Block -Protocol 145 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 146 (Unassigned)" -Direction Inbound -Action Block -Protocol 146 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 147 (Unassigned)" -Direction Inbound -Action Block -Protocol 147 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 148 (Unassigned)" -Direction Inbound -Action Block -Protocol 148 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 149 (Unassigned)" -Direction Inbound -Action Block -Protocol 149 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 150 (Unassigned)" -Direction Inbound -Action Block -Protocol 150 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 151 (Unassigned)" -Direction Inbound -Action Block -Protocol 151 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 152 (Unassigned)" -Direction Inbound -Action Block -Protocol 152 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 153 (Unassigned)" -Direction Inbound -Action Block -Protocol 153 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 154 (Unassigned)" -Direction Inbound -Action Block -Protocol 154 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 155 (Unassigned)" -Direction Inbound -Action Block -Protocol 155 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 156 (Unassigned)" -Direction Inbound -Action Block -Protocol 156 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 157 (Unassigned)" -Direction Inbound -Action Block -Protocol 157 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 158 (Unassigned)" -Direction Inbound -Action Block -Protocol 158 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 159 (Unassigned)" -Direction Inbound -Action Block -Protocol 159 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 160 (Unassigned)" -Direction Inbound -Action Block -Protocol 160 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 161 (Unassigned)" -Direction Inbound -Action Block -Protocol 161 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 162 (Unassigned)" -Direction Inbound -Action Block -Protocol 162 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 163 (Unassigned)" -Direction Inbound -Action Block -Protocol 163 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 164 (Unassigned)" -Direction Inbound -Action Block -Protocol 164 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 165 (Unassigned)" -Direction Inbound -Action Block -Protocol 165 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 166 (Unassigned)" -Direction Inbound -Action Block -Protocol 166 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 167 (Unassigned)" -Direction Inbound -Action Block -Protocol 167 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 168 (Unassigned)" -Direction Inbound -Action Block -Protocol 168 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 169 (Unassigned)" -Direction Inbound -Action Block -Protocol 169 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 170 (Unassigned)" -Direction Inbound -Action Block -Protocol 170 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 171 (Unassigned)" -Direction Inbound -Action Block -Protocol 171 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 172 (Unassigned)" -Direction Inbound -Action Block -Protocol 172 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 173 (Unassigned)" -Direction Inbound -Action Block -Protocol 173 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 174 (Unassigned)" -Direction Inbound -Action Block -Protocol 174 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 175 (Unassigned)" -Direction Inbound -Action Block -Protocol 175 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 176 (Unassigned)" -Direction Inbound -Action Block -Protocol 176 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 177 (Unassigned)" -Direction Inbound -Action Block -Protocol 177 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 178 (Unassigned)" -Direction Inbound -Action Block -Protocol 178 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 179 (Unassigned)" -Direction Inbound -Action Block -Protocol 179 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 180 (Unassigned)" -Direction Inbound -Action Block -Protocol 180 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 181 (Unassigned)" -Direction Inbound -Action Block -Protocol 181 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 182 (Unassigned)" -Direction Inbound -Action Block -Protocol 182 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 183 (Unassigned)" -Direction Inbound -Action Block -Protocol 183 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 184 (Unassigned)" -Direction Inbound -Action Block -Protocol 184 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 185 (Unassigned)" -Direction Inbound -Action Block -Protocol 185 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 186 (Unassigned)" -Direction Inbound -Action Block -Protocol 186 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 187 (Unassigned)" -Direction Inbound -Action Block -Protocol 187 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 188 (Unassigned)" -Direction Inbound -Action Block -Protocol 188 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 189 (Unassigned)" -Direction Inbound -Action Block -Protocol 189 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 190 (Unassigned)" -Direction Inbound -Action Block -Protocol 190 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 191 (Unassigned)" -Direction Inbound -Action Block -Protocol 191 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 192 (Unassigned)" -Direction Inbound -Action Block -Protocol 192 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 193 (Unassigned)" -Direction Inbound -Action Block -Protocol 193 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 194 (Unassigned)" -Direction Inbound -Action Block -Protocol 194 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 195 (Unassigned)" -Direction Inbound -Action Block -Protocol 195 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 196 (Unassigned)" -Direction Inbound -Action Block -Protocol 196 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 197 (Unassigned)" -Direction Inbound -Action Block -Protocol 197 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 198 (Unassigned)" -Direction Inbound -Action Block -Protocol 198 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 199 (Unassigned)" -Direction Inbound -Action Block -Protocol 199 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 200 (Unassigned)" -Direction Inbound -Action Block -Protocol 200 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 201 (Unassigned)" -Direction Inbound -Action Block -Protocol 201 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 202 (Unassigned)" -Direction Inbound -Action Block -Protocol 202 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 203 (Unassigned)" -Direction Inbound -Action Block -Protocol 203 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 204 (Unassigned)" -Direction Inbound -Action Block -Protocol 204 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 205 (Unassigned)" -Direction Inbound -Action Block -Protocol 205 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 206 (Unassigned)" -Direction Inbound -Action Block -Protocol 206 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 207 (Unassigned)" -Direction Inbound -Action Block -Protocol 207 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 208 (Unassigned)" -Direction Inbound -Action Block -Protocol 208 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 209 (Unassigned)" -Direction Inbound -Action Block -Protocol 209 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 210 (Unassigned)" -Direction Inbound -Action Block -Protocol 210 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 211 (Unassigned)" -Direction Inbound -Action Block -Protocol 211 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 212 (Unassigned)" -Direction Inbound -Action Block -Protocol 212 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 213 (Unassigned)" -Direction Inbound -Action Block -Protocol 213 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 214 (Unassigned)" -Direction Inbound -Action Block -Protocol 214 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 215 (Unassigned)" -Direction Inbound -Action Block -Protocol 215 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 216 (Unassigned)" -Direction Inbound -Action Block -Protocol 216 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 217 (Unassigned)" -Direction Inbound -Action Block -Protocol 217 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 218 (Unassigned)" -Direction Inbound -Action Block -Protocol 218 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 219 (Unassigned)" -Direction Inbound -Action Block -Protocol 219 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 220 (Unassigned)" -Direction Inbound -Action Block -Protocol 220 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 221 (Unassigned)" -Direction Inbound -Action Block -Protocol 221 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 222 (Unassigned)" -Direction Inbound -Action Block -Protocol 222 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 223 (Unassigned)" -Direction Inbound -Action Block -Protocol 223 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 224 (Unassigned)" -Direction Inbound -Action Block -Protocol 224 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 225 (Unassigned)" -Direction Inbound -Action Block -Protocol 225 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 226 (Unassigned)" -Direction Inbound -Action Block -Protocol 226 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 227 (Unassigned)" -Direction Inbound -Action Block -Protocol 227 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 228 (Unassigned)" -Direction Inbound -Action Block -Protocol 228 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 229 (Unassigned)" -Direction Inbound -Action Block -Protocol 229 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 230 (Unassigned)" -Direction Inbound -Action Block -Protocol 230 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 231 (Unassigned)" -Direction Inbound -Action Block -Protocol 231 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 232 (Unassigned)" -Direction Inbound -Action Block -Protocol 232 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 233 (Unassigned)" -Direction Inbound -Action Block -Protocol 233 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 234 (Unassigned)" -Direction Inbound -Action Block -Protocol 234 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 235 (Unassigned)" -Direction Inbound -Action Block -Protocol 235 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 236 (Unassigned)" -Direction Inbound -Action Block -Protocol 236 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 237 (Unassigned)" -Direction Inbound -Action Block -Protocol 237 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 238 (Unassigned)" -Direction Inbound -Action Block -Protocol 238 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 239 (Unassigned)" -Direction Inbound -Action Block -Protocol 239 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 240 (Unassigned)" -Direction Inbound -Action Block -Protocol 240 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 241 (Unassigned)" -Direction Inbound -Action Block -Protocol 241 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 242 (Unassigned)" -Direction Inbound -Action Block -Protocol 242 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 243 (Unassigned)" -Direction Inbound -Action Block -Protocol 243 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 244 (Unassigned)" -Direction Inbound -Action Block -Protocol 244 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 245 (Unassigned)" -Direction Inbound -Action Block -Protocol 245 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 246 (Unassigned)" -Direction Inbound -Action Block -Protocol 246 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 247 (Unassigned)" -Direction Inbound -Action Block -Protocol 247 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 248 (Unassigned)" -Direction Inbound -Action Block -Protocol 248 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 249 (Unassigned)" -Direction Inbound -Action Block -Protocol 249 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 250 (Unassigned)" -Direction Inbound -Action Block -Protocol 250 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 251 (Unassigned)" -Direction Inbound -Action Block -Protocol 251 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 252 (Unassigned)" -Direction Inbound -Action Block -Protocol 252 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 253 (Unassigned)" -Direction Inbound -Action Block -Protocol 253 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 254 (Unassigned)" -Direction Inbound -Action Block -Protocol 254 -Profile Any
New-NetFirewallRule -DisplayName "Block Protocol 255 (Reserved)" -Direction Inbound -Action Block -Protocol 255 -Profile Any


# New-NetFirewallRule -DisplayName "Block Protocol 4 (IPv4)"      -Direction Inbound -Action Block -Protocol 4  -Profile Any
# New-NetFirewallRule -DisplayName "Block Protocol 6 (TCP)"       -Direction Inbound -Action Block -Protocol 6  -Profile Any
# New-NetFirewallRule -DisplayName "Block Protocol 17 (UDP)"        -Direction Inbound -Action Block -Protocol 17 -Profile Any